#pragma once

namespace Luch::Vulkan
{
    class VulkanCommandBuffer;
    class VulkanCommandPool;
    class VulkanCubeTexture;
    class VulkanDeviceBuffer;
    class VulkanDeviceBufferView;
    class VulkanDescriptorPool;
    class VulkanDescriptorSet;
    class VulkanDescriptorSetBinding;
    class VulkanDescriptorSetLayout;
    struct VulkanDescriptorSetLayoutCreateInfo;
    class DescriptorSetLayoutCreateInfo;
    class VulkanDescriptorSetWrites;
    class VulkanFence;
    class VulkanFramebuffer;
    class VulkanFramebufferCreateInfo;
    class VulkanGlslShaderCompiler;
    class VulkanGraphicsDevice;
    class VulkanImage;
    class VulkanImageView;
    class VulkanIndexBuffer;
    class VulkanPhysicalDevice;
    class VulkanPipeline;
    struct VulkanPipelineBarrier;
    class VulkanPipelineCache;
    class VulkanPipelineLayout;
    struct VulkanPipelineLayoutCreateInfo;
    class PipelineLayoutCreateInfo;
    class VulkanPresentQueue;
    class VulkanQueue;
    class VulkanRenderPass;
    class VulkanRenderPassCreateInfo;
    struct VulkanRenderPassCreateInfoData;
    class VulkanSampler;
    class VulkanSemaphore;
    class VulkanShaderCompiler;
    class VulkanShaderModule;
    class VulkanSubpassDescription;
    class VulkanSurface;
    class VulkanSwapchain;

    struct VulkanGraphicsPipelineCreateInfo;
    struct VulkanImageDescriptorInfo;
    struct VulkanSubpassCreateInfo;
    struct VulkanSwapchainCreateInfo;
    struct VulkanQueueInfo;
}
