#pragma once

namespace Husky::Vulkan
{
    class CommandBuffer;
    class CommandPool;
    class CubeTexture;
    class DeviceBuffer;
    class DeviceBufferView;
    class DescriptorPool;
    class DescriptorSet;
    class DescriptorSetBinding;
    class DescriptorSetLayout;
    class DescriptorSetLayoutCreateInfo;
    class DescriptorSetWrites;
    class Fence;
    class Framebuffer;
    class FramebufferCreateInfo;
    class GlslShaderCompiler;
    class GraphicsDevice;
    class Image;
    class ImageView;
    class IndexBuffer;
    class PhysicalDevice;
    class Pipeline;
    class PipelineBarrier;
    class PipelineCache;
    class PipelineLayout;
    class PipelineLayoutCreateInfo;
    class PresentQueue;
    class Queue;
    class RenderPass;
    class RenderPassCreateInfo;
    class Sampler;
    class SamplerObject;
    class Semaphore;
    class ShaderCompiler;
    class ShaderModule;
    class SubpassDescription;
    class Surface;
    class Swapchain;
    class VertexBuffer;

    struct GraphicsPipelineCreateInfo;
    struct ImageDescriptorInfo;
    struct SubpassCreateInfo;
    struct SwapchainCreateInfo;
    struct QueueInfo;
}
